---
engines:
  rubocop:
    enabled: true
  fixme:
    enabled: true
    exclude_paths:
      - config/engines.yml
ratings:
  paths:
  - "**.rb"
exclude_paths:
  - .bundle/
  - spec/**/*
  - benchmarks/**/*
